[global]


# =====================
# default setting will be inherited
[default]
prefix = "dev-cfchou-me"
app_name = "dev-cfchou.me"

# Can overwrite CDK_DEFAULT_ACCOUNT & CDK_DEFAULT_REGION in environment
#cdk_default_account = "897882544000"
#cdk_default_region = "ap-southeast-1"

[default.restapi.throttle]
# usage plan limit
rate = 50
burst = 100

[default.cicd]
connection_arn = "arn:aws:codestar-connections:ap-southeast-1:897882544000:connection/183630a4-d3f9-4ba3-943e-a025872036a1"
repo = "cfchou/playground"
branch = "develop"


# =====================
# setting in dev
# take most of setting from [default] and its nested tables
[dev]


# =====================
# setting in prod
[prod]
prefix = "cfchou-me"
app_name = "cfchou.me"

[prod.restapi.throttle]
# usage plan limit
rate = 100
burst = 200

[prod.cicd]
# NOTE: Can't partially overwrite nested default. It's probably a problem in
#  dynaconf:
# https://github.com/rochacbruno/dynaconf/issues/649#issuecomment-907610695
connection_arn = "arn:aws:codestar-connections:ap-southeast-1:897882544000:connection/183630a4-d3f9-4ba3-943e-a025872036a1"
repo = "cfchou/playground"
branch = "master"

